---
title: "Dataviz étranger en Suisse"
author: "Duc-Quang Nguyen"
date: "21 January 2016"
output: html_document
---

### Data 

##### Link 
* [Population résidante permanente et non permanente selon les niveaux géographiques institutionnels, le sexe, la nationalité et l'âge](https://www.pxweb.bfs.admin.ch/Selection.aspx?px_language=fr&px_db=px-x-0103010000_101&px_tableid=px-x-0103010000_101\px-x-0103010000_101.px&px_type=PX)

#### Select 
 * 2014
 * Suisse
 * Type de population -> tout
 * sexe - Total
 * Autorisation de résidence -> tout sauf Autorisation de résidence - total (10)
 * Classe d'âge total
 * Nationalité -> tout sauf Nationalité - total (201)

40020 cellules sélectionées and Saved as : px-x-0103010000_101.csv

### Open and clean up: remove non-needed columns

### Open with Google Refine, set the encoding to latin and export as CSV: px-x-0103010000_101_cleaned_refined.csv

```{r}

library(dplyr)
library(tidyr)
library(readr)
library(swiMap)
library(countrycode)

###  -------------------------------------------------------------------------------------------------------------
###      SETTINGS
###  -------------------------------------------------------------------------------------------------------------  

plotByVisa <- FALSE

data.read <- read_csv("data/px-x-0103010000_101_cleaned_refined.csv")
txt <- read.csv("data/translations_sunburst_foreigners.csv", row.names = 1, stringsAsFactors = F)
n.threshold.merge <- 1000

# wide to long transform
data <- data.read %>% gather(country, value, 3:ncol(data.read))

# filter the pop non-permanent
data %>% filter(`Type de population` == "Population résidante permanente") %>% 
# sum the values by the pop permanente / non-permanente
  group_by(`Autorisation de résidence`, country) %>% 
  dplyr::summarise(tot = sum(value, na.rm = T)) %>% ungroup() -> data

# Remove Suisses!
data <- filter(data, data$country != "Suisse")
data$country <- as.character(data$country)

totForeigners <- sum(data$tot)

## replace unknow origin by "Inconu"
data <- data %>% mutate(country = replace(country,
  country %in% c('Apatride', "Non attribuable selon frontières actuelles", "Sans indication"),
  "inconnu"))

## match country names to translation
idx <- match(unique(data$country), countryTranslations$FR)
unique(data$country)[which(is.na(idx))]

## Hack to rename unmatched countries
countries_rename <- 
  c("Arabie saoudite"       , "autres pays"                 , "Azerbaïdjan"            , "Bosnie et Herzégovine"  ,
    "Congo (Brazzaville)"     , "Congo (Kinshasa)"       , "Corée (Sud)"            , "Côte d'Ivoire"          ,
    "Danemark"                , "Egypte"                 , "Equateur"               , "Erythrée"               ,
    "Etats-Unis"              , "Ethiopie"               , "Haïti"                  , "inconnu"                ,
    "Irak"                    , "Iran"                   , "Kosovo"                 , "Macédoine"              ,
    "Moldova"                 , "République dominicaine" , "République tchèque"     , "Russie"                 ,
    "Taïwan (Taipei chinois)" , "Vietnam" 
) 

names(countries_rename) <- 
  c('Arabie Saoudite', 'autres pays', 'Azerbaédjan', 'Bosnie-Herzégovine',
    'Congo', 'La République démocratique du Congo', 'République de Corée', "Côte d'ivoire",
    'Denmark', "Égypte", "Équateur", "Érythrée",
    "États-Unis", "Éthiopie", "Haiti", "inconnu",
    "Iraq", "République Islamique d'Iran", "Kosovo", "Macédoine",
    "Moldavie", "Dominicaine république", "République tchéque", "Fédération de Russie",
    "Taïwan, Province de Chine", "Viet Nam"
  )

# replace names by hack
data <- as.data.frame(data)
idx <- which(data$country %in% countries_rename)
data[idx,'country'] <- names(countries_rename)[
  match(data[idx,'country'] %>% unlist(use.names = F), countries_rename)]

stopifnot(sum(data$tot) == totForeigners)

## Continent match
countries <- data.frame(country = unique(data$country))
countries$iso2 <- countryTranslations[match(countries$country,countryTranslations$FR), 'iso2']
countries$continent <- countrycode(countries$iso2, "iso2c", "continent")

## Hack for non matched country to continent 
continent.hack <- c(
  "Cité du Vatican", "Macédoine", "Kosovo", "Brunéi Darussalam",
  "Taïwan, Province de Chine", "Laos", "Corée (Nord)", "Emirats arabes unis", "Palestine", 
  "Iles Salomon", "Iles Marshall", "Micronésie", "inconnu"
)
names(continent.hack) <- c(
  "Europe", "Europe", "Europe", "Asia",
  "Asia", "Asia", "Asia", "Asia", "Asia",
  "Oceania", "Oceania", "Oceania", "inconnu"
)

idx <- which(countries$country %in% continent.hack)
countries[idx,'continent'] <- names(continent.hack)

stopifnot(!any(is.na(countries$continent)))
#countries[which(is.na(countries$continent)),]
# add continent !
data$continent <- countries[match(data$country, countries$country), 'continent']
stopifnot(sum(data$tot) == totForeigners)

## find the top country
sum <- data %>% group_by(country) %>% dplyr::summarise(value = sum(tot, na.rm = T)) %>% 
  ungroup() %>% arrange(desc(value))
hist(sum$value, breaks = 1000)
sum[sum$value < n.threshold.merge,'country'] %>% unlist(use.name = F) -> countries.sub
stopifnot(sum(sum$value) == totForeigners)

# replace unfrequent country by "autres"
data <- data %>% mutate(country = replace(country,
  country %in% countries.sub,
  "autres pays"))

# shape the data for plot, recompute total values
data %>% group_by(country, continent) %>% 
  dplyr::summarise(value = sum(tot, na.rm = T)) %>% ungroup() -> dd
stopifnot(sum(dd$value) == totForeigners)

######  check country translation present! ################
idx <- match(unique(data$country), countryTranslations$FR)
toTranslate <- unique(data$country)[which(is.na(idx))]

idx.m <- sapply(idx[!is.na(idx)], function(i) {
  any(is.na(countryTranslations[i,]) | countryTranslations[i,] == "")  
})

if(any(idx.m)) stop()

# create tmp translation file
# trl <- data.frame(code = c(
#   paste0(gsub(" ", "", toTranslate), ".country"), paste0(unique(data$continent), ".continent")),
#   fr = c(toTranslate, unique(data$continent))
# )
# write.csv(trl, file = "data/translations_tmp.csv", row.names = F) 

###  -------------------------------------------------------------------------------------------------------------
###      PLOT SUNBURST
###  -------------------------------------------------------------------------------------------------------------  

library(pipeR)
library(swiRcharts)
library(sunburstR)
library(htmlwidgets)



countries <- unique(dd$country)
idx <- match(countries, countryTranslations$FR)

sapply('FR', function(lang) {
#sapply(lang %in% colnames(txt)) {

  names(countries) <- countryTranslations[idx, lang]
  names(countries)[which(is.na(names(countries)))] <- txt[paste0(gsub(" ", "", countries[which(is.na(names(countries)))]), ".country"), lang]
  
  stopifnot(!any(is.na(names(countries))))
  
  df <- dd
  df$country <- names(countries)[match(df$country, countries)]
  stopifnot(!any(is.na(df$country)))
  
  df$continent <- txt[paste0(df$continent,".continent"), lang]
  stopifnot(!any(is.na(df$continent)))
  
  # create the sequence data
  seqd <- data.frame(
    sequence = paste(df$continent, gsub("(\\-|\\,)", " ", df$country), sep = "-"), 
    freq = df$value
  )

  schart <- seqd %>>% sunburst(
    count = T, colors = c(rev(swiTheme::swi_rpal[1:16]), 
    rep(swiTheme::swi_rpal[1:16], 10)), legendOrder = "")
  
  # hack
  schart$sizingPolicy$browser$padding <- 1
  schart$sizingPolicy$browser$defaultWidth <- "100%"
  
  saveWidget(schart, file = "swissForeigners_sunburst_tmp.html", selfcontained = FALSE, libdir = "js")
  
  swi_widget("swissForeigners_sunburst_tmp.html", paste0("swissForeigners_sunburst_", lang, ".html"),
    h2 = txt['title', lang], 
    descr = paste0(txt['descr', lang], "<br><br>","<i>", txt['descr2', lang], "</i>"),
    h3 = "",
    source = paste0(txt['source',lang], ": ", htmlLink("https://www.pxweb.bfs.admin.ch/Selection.aspx?px_language=fr&px_db=px-x-0103010000_101&px_tableid=px-x-0103010000_101%5Cpx-x-0103010000_101.px&px_type=PX", 
      txt['source.name', lang]),
     " | ",  txt['code', lang], ": ", htmlLink("https://github.com/timelyportfolio/sunburstR", "sunburstR"))
  )
})



if(plotByVisa) {
 # shape the data for plot, recompute total values
data %>% group_by(`Autorisation de résidence`) %>% dplyr::summarise(alue = sum(tot, na.rm = T)) %>% 
  ungroup()

ddd <- data %>% 
  mutate(`Autorisation de résidence` = ifelse(`Autorisation de résidence` %in% 
  c('Diplomate, fonctionnaire international avec immunité diplomatique', 
    'Fonctionnaire international sans immunité diplomatique'), 
    "international", `Autorisation de résidence`))  %>%
  mutate(`Autorisation de résidence` = ifelse(`Autorisation de résidence` ==
    "Personne admise à titre provisoire (F)", 
    "provisoire (F)", `Autorisation de résidence`))  %>%
  mutate(`Autorisation de résidence` = ifelse(`Autorisation de résidence` ==
    "Requérant d'asile (N)", 
    "asile (N)", `Autorisation de résidence`))  %>% 
  mutate(`Autorisation de résidence` = ifelse(`Autorisation de résidence` ==
    "Titulaire d'une autorisation d'établissement (C)", 
    "permis C", `Autorisation de résidence`))  %>% 
  mutate(`Autorisation de résidence` = ifelse(`Autorisation de résidence` ==
    "Titulaire d'une autorisation de séjour (B)", 
    "permis B", `Autorisation de résidence`))  %>%  
  mutate(`Autorisation de résidence` = ifelse(`Autorisation de résidence` ==
    "Titulaire d'une autorisation de séjour de courte durée (L)", 
    "courte L", `Autorisation de résidence`))  %>%  
  mutate(`Autorisation de résidence` = ifelse(`Autorisation de résidence` ==
    "Titulaire d'une autorisation de séjour avec activité lucrative (Ci)", 
    "permis Ci", `Autorisation de résidence`))
  

ddd %>% group_by(continent, `Autorisation de résidence`, country) %>% 
  dplyr::summarise(value = sum(tot, na.rm = T)) %>% ungroup() -> ddd
stopifnot(sum(ddd$value) == totForeigners)

seq2 <- paste(gsub("(\\-|\\,)", " ", ddd$`Autorisation de résidence`), ddd$continent, 
  gsub("(\\-|\\,)", " ", ddd$country), sep = "-")
seqd2 <- data.frame(sequence = seq2, freq = ddd$value)

schart2 <- seqd2 %>>% sunburst(
  count = T, colors = rep(swiTheme::swi_rpal[1:16], 10))


 # hack
schart2$sizingPolicy$browser$padding <- 1
schart2$sizingPolicy$browser$defaultWidth <- "100%"
schart2$sizingPolicy$browser$defaultHeight <- 500
  
saveWidget(schart2, file = "swissForeigners2_sunburst_tmp.html", selfcontained = FALSE, libdir = "js")
  
  swi_widget("swissForeigners2_sunburst_tmp.html", paste0("swissForeignersPermis_sunburst_", 'fr', ".html"),
    h2 = "Les étrangers de Suisse",
    descr = paste0("La Suisse compte 2 millions d'étrangers, soit un quart de sa population permanente. Ce graphique montre le type de permis de séjour, le continent et la nationalité d'origine des 2 millions d'étrangers en Suisse en 2014", "<br><br><i>", "Placez votre curseur ou tapoter sur une région du graphique pour voir les chiffres exacts</i>"),
    h3 = "",
    source = paste0(txt['source',lang], ": ", txt['source.name', lang],
     " | ",  txt['code', lang], ": sunburstR")
  )
  
}